# Generated by Django 4.2 on 2023-05-08 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NivelMembro',
            fields=[
                ('pontos_necessarios', models.IntegerField()),
                ('recompensa', models.CharField(blank=True, max_length=50)),
                ('id_nivel', models.IntegerField(choices=[(1, 'Iniciante'), (2, 'Intermédio'), (3, 'Avançado'), (4, 'Profissional')], default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1)),
                ('imagem_perfil', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('data_nascimento', models.DateField()),
                ('pontos', models.IntegerField(default=0)),
                ('nivel_membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webdanceteria.nivelmembro')),
                ('preferencias_musicais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webdanceteria.categoria')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1)),
                ('imagem_perfil', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('data_nascimento', models.DateField()),
                ('especializacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webdanceteria.categoria')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField()),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('imagem', models.CharField(blank=True, max_length=100, null=True)),
                ('preco_bilhete', models.DecimalField(decimal_places=2, max_digits=6)),
                ('artistas', models.CharField(blank=True, max_length=500, null=True)),
                ('bilhetes_disponiveis', models.IntegerField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webdanceteria.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bilhete', models.IntegerField()),
                ('data_compra', models.DateTimeField()),
                ('data_validade', models.DateTimeField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webdanceteria.utilizador')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webdanceteria.evento')),
            ],
        ),
        migrations.CreateModel(
            name='AulaDanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=100)),
                ('data_hora', models.DateTimeField(null=True)),
                ('preco_bilhete', models.DecimalField(decimal_places=2, default=None, max_digits=6)),
                ('bilhetes_disponiveis', models.IntegerField(default=10)),
                ('participantes', models.IntegerField(null=True)),
                ('nivel_aconselhado', models.IntegerField(choices=[(1, 'Iniciante'), (2, 'Intermediário'), (3, 'Avançado'), (4, 'Profissional')])),
                ('instrutor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webdanceteria.instrutor')),
            ],
        ),
    ]
