# Generated by Django 4.2 on 2023-05-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdanceteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='preferencias_musicais',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
