# Generated by Django 4.2 on 2023-05-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdanceteria', '0002_alter_utilizador_preferencias_musicais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelmembro',
            name='id_nivel',
            field=models.IntegerField(choices=[(1, 'Iniciante'), (2, 'Intermédio'), (3, 'Avançado'), (4, 'Profissional')], primary_key=True, serialize=False),
        ),
    ]
