# Generated by Django 4.2 on 2023-05-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdanceteria', '0005_alter_instrutor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilhete',
            name='numero_bilhete',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='categoria',
        ),
    ]
