# Generated by Django 4.2 on 2023-05-09 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdanceteria', '0006_remove_bilhete_numero_bilhete_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bilhete',
            new_name='BilheteEvento',
        ),
        migrations.CreateModel(
            name='BilheteAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateTimeField()),
                ('data_validade', models.DateTimeField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webdanceteria.auladanca')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webdanceteria.utilizador')),
            ],
        ),
    ]
