# Generated by Django 4.2 on 2023-05-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdanceteria', '0007_rename_bilhete_bilheteevento_bilheteaula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auladanca',
            name='participantes',
            field=models.IntegerField(default=0),
        ),
    ]
