# Generated by Django 4.1.7 on 2023-05-11 15:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webdanceteria', '0008_alter_auladanca_participantes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilizador',
            new_name='Membro',
        ),
    ]
