# Generated by Django 4.1.7 on 2023-05-11 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webdanceteria', '0009_rename_utilizador_membro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auladanca',
            name='nivel_aconselhado',
            field=models.IntegerField(choices=[(1, 'Iniciante'), (2, 'Intermédio'), (3, 'Avançado'), (4, 'Profissional')]),
        ),
        migrations.AlterField(
            model_name='bilheteaula',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='webdanceteria.membro'),
        ),
        migrations.AlterField(
            model_name='bilheteevento',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='webdanceteria.membro'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='preco_bilhete',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1)),
                ('imagem_perfil', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('data_nascimento', models.DateField()),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
