# Generated by Django 4.1.7 on 2023-05-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdanceteria', '0012_alter_diretor_imagem_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.FileField(null=True, upload_to='webdanceteria/static/webdanceteria/eventoImg'),
        ),
    ]
