# Generated by Django 4.1.7 on 2023-05-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdanceteria', '0016_alter_bilheteaula_aula_alter_bilheteaula_comprador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelmembro',
            name='especial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nivelmembro',
            name='tipo_recompensa',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
