# Generated by Django 4.1.7 on 2023-05-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdanceteria', '0017_nivelmembro_especial_nivelmembro_tipo_recompensa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivelmembro',
            name='especial',
        ),
        migrations.RemoveField(
            model_name='nivelmembro',
            name='tipo_recompensa',
        ),
        migrations.AddField(
            model_name='bilheteaula',
            name='especial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bilheteevento',
            name='especial',
            field=models.BooleanField(default=False),
        ),
    ]
