# Generated by Django 4.2.1 on 2023-05-14 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webdanceteria', '0020_alter_auladanca_nivel_aconselhado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auladanca',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=100)),
                ('descricao', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('rating', models.IntegerField()),
                ('data_avaliacao', models.DateTimeField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webdanceteria.evento')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
