# Generated by Django 4.2.1 on 2023-05-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdanceteria', '0022_remove_avaliacao_utilizador_avaliacao_avaliador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diretor',
            name='n_aulas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diretor',
            name='n_eventos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instrutor',
            name='n_aulas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instrutor',
            name='n_eventos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membro',
            name='n_aulas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membro',
            name='n_eventos',
            field=models.IntegerField(default=0),
        ),
    ]
